### ISSUE TITLE
about the code release

### ISSUE THREAD

**Issue by amiltonwong** [jisuk1/pllay#1]
Hi, @jisuk1 ,

Congratulations on the coming NeurIPS acceptance. When will the code be released?

**Comment by jkim82133** [comment]
Hello @amiltonwong ,

Thank you for your interest in our paper and sorry for being delayed. We are still cleaning the code, but the code will be released this week.

**Comment by xujinzh** [comment]
When will the code be released?

**Comment by qizhaoaoe** [comment]
Thanks for your idea! Does it support 3D images?

**Comment by amiltonwong** [comment]
Hi, @jisuk1 ,

Any update news on the code release?

Thanks~

**Comment by jkim82133** [comment]
@amiltonwong @xujinzh Sorry for being delayed. The code is available now.
@qizhaoaoe Yes, it can take 3D images (or in general n-dimensional images) as inputs.
